services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka_fishing_etl
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - fishing_network

  airflow:
    build: .
    container_name: airflow_fishing
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "TH-odGQzGXpNAu22IhEEkFfhDZ663iOOFBQUcpMzhg4=" 
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/project
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@test.com || true &&
      (airflow webserver & airflow scheduler)
      "
    networks:
      - fishing_network

networks:
  fishing_network:
    driver: bridge